spring:
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
          defaultCandidate: false
        kafka1:
          type: kafka
          defaultCandidate: true
